@echo off
echo Creating test virtual environment...
python -m venv test_venv

echo Activating virtual environment...
call test_venv\Scripts\activate.bat

echo Installing test dependencies...
python -m pip install -r tests\requirements-test.txt

echo Running tests...
python -m pytest tests\test_language_service.py tests\test_metrics_service.py -v

echo Deactivating virtual environment...
deactivate
