version: 2.1
jobs:
  run-docker-compose:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Run Docker Compose (build and up)
          command: docker-compose up --build -d
workflows:
  version: 2
  docker-compose-workflow:
    jobs:
      - run-docker-compose