apiVersion: 1

datasources:
  - name: B2B Sales Backend
    type: grafana-simple-json-datasource
    access: proxy
    url: http://b2b-sales-backend:3001/api/admin/grafana
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      httpMethod: "GET" 